### ISSUE TITLE
[BUG] "An error occurred while rendering this content" on boot

### ISSUE THREAD

**Issue by VAggrippino** [SteamDeckHomebrew/decky-loader#838]
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

After a SteamOS update to 3.7.17, BUILD_ID=20251027.1, (the one that enabled display-off downloads), I get an error when I boot.

This occurs after the startup movie, mostly, but sometimes it'll play part of the startup movie then show the error then start the startup movie from the start again before showing the error again.

```
An error occurred while rendering this content.

Error Reference: Shared SteamUI_10242686_02aa30fa90a03672
Decky Version: v3.2.0
```

And it continues on with `Minified React error #31`, followed by a link to https://react.dev/errors/31?args%5B%5D=object%20with%20keys%20%7B%7D

I've tried:  
- checking for updates with the other Decky Loader branches from the buttons shown on the error screen
- uninstalling and re-installing Decky Loader
- removing all the plugins (manually, using `rm -r` in `~/homebrew/plugins`. Even with no plugins at all, I still get the error when I try to boot.

It seems that the only solution right now is to uninstall Decky Loader.

I have a Steam Deck system report text file and pictures of the screen with the full text of the error if any of that helps.

Thank you.

### Expected Behaviour

Boot into SteamOS and show the home screen.

### SteamOS version

SteamOS 3.7.17

### Selected Update Channel

Stable

### Decky Loader Version

3.2.0

### Plugin Info

I had some plugins installed when I first experienced this issue, but I uninstalled Decky Loader, removed `~/homebrew`,  and reinstalled Decky Loader with no plugins. The problem still occurs with this _clean_ installation of Decky Loader.

### Have you modified the read-only filesystem at any point?

No

### Backend Logs

[20251118_110727_deckylog.txt](https://github.com/user-attachments/files/23609631/20251118_110727_deckylog.txt)

### Frontend Logs

[20251118_111041_cef_log.txt](https://github.com/user-attachments/files/23609640/20251118_111041_cef_log.txt)

[20251118_111041_cef_log.previous.txt](https://github.com/user-attachments/files/23609643/20251118_111041_cef_log.previous.txt)

**Comment by zegar7** [comment]
Fully reinstalling decky and all plugins seemed to work for me. I didn't have any useful data in the decky folder so I didn't mind redoing it all, however it might not be the case for everyone else.

**Comment by VAggrippino** [comment]
> Fully reinstalling decky and all plugins seemed to work for me. I didn't have any useful data in the decky folder so I didn't mind redoing it all, however it might not be the case for everyone else.

Uninstalling and reinstalling was one of the things I tried. When I reinstalled Decky Loader I saw that all the plugins were still there. So, I did some reading and decided to uninstall _and_ delete `~/homebrew`. Then I reinstalled and the plugins weren't there.

The reason I know whether or not the plugins were still there is that I can usually get back into the Steam UI if I mash the _[STEAM]_ button repeatedly. Then I can look at the list of Decky plugins with _[...]_. It usually goes back to the error screen before I do much though.

Where's the "decky" folder? I didn't check for anything past removing `~/homebrew`. Are there more steps to fully uninstalling Decky Loader?

**Comment by VAggrippino** [comment]
Somebody suggested that Junk Store might be the problem and that its latest update might be the solution. This is the standalone Junk Store 2 that I paid for so that I can easily integrate my GOG games into Steam OS.

There was some discussion of a similar problem at Junk Store's Discord server and it seems like the update solved it for them.

I updated Junk Store and re-installed Decky Loader, but I still can't boot up without that error message unless I uninstall Decky Loader.

**Comment by christopherbmcclay-code** [comment]
I had this issue, kept removing plugins until it booted. Removed emudecky and emudeck achievements. After that I got a pop up of deck settings and wine cellar failing to load by steam. So I removed them, uninstalled and reinstalled decky loader and it booted. I fumbled about and this was my fix.

**Comment by VAggrippino** [comment]
> I had this issue, kept removing plugins until it booted. Removed emudecky and emudeck achievements. After that I got a pop up of deck settings and wine cellar failing to load by steam. So I removed them, uninstalled and reinstalled decky loader and it booted. I fumbled about and this was my fix.

One of the first things I did while I was trying to fix this myself is remove all the plugins. Even with no plugins installed I'll get the error message I reported if Decky Loader is installed.

I wasn't using emudeck achievements or wine cellar.

**Comment by BananaAcid** [comment]
What worked for me:
In desktop mode, I changed the homebrew/plugin/* owner to ’deck’ in Konsole  to be able to remove 2 plugins (that killed Decky) with Dolphin (reboot changes the owner back to root):
- Emuchivements
- RemotePlayWhatever

This was broken for me too:
- ReShadeDeck

**Comment by VAggrippino** [comment]
> In desktop mode, changed the homebrew/plugin/* owner to ’deck’ in Konsole to be able to remove the 2 killing plugins with Dolphin (reboot changes the owner back to root):
> 
> * Emuchivements
> * RemotePlayWhatever
> 
> This was broken for me too:
> 
> * ReShadeDeck

I just used `sudo`, so the owner/permissions of the files weren't an issue for me. I didn't use any of those plugins, but I removed **all** of my plugins and still have the problem. If Decky Loader is installed, even with no plugins, I get the error message I reported.

**Comment by Rumik** [comment]
I'm having the same problem. I've tried uninstalling some plugins but there's no change.

**Comment by jullson2** [comment]
Please fix this. Can't load Decky at all since the latest stable SteamOS update.

**Comment by ynhhoJ** [comment]
I checked the issue author logs and found multiple errors, ex:

<img width="2414" height="405" alt="Image" src="https://github.com/user-attachments/assets/a98f41d3-2a2c-4e2b-b809-6739bd8eac0a" />

<img width="2414" height="405" alt="Image" src="https://github.com/user-attachments/assets/4000fa9c-4cba-43dc-8abf-f7f49cfc1a8e" />

<img width="2414" height="405" alt="Image" src="https://github.com/user-attachments/assets/fb556be0-59d7-4963-91c1-ac95470dc439" />

After you clear your `plugins` folder, make sure that you make a reboot in order to see if everything was fixed.

P.S: I'm on latest Beta Steam Update with same Decky version as author, but on my machine everything is fine 🤔 

There is not enough details what you guys have in common what can cause this error

**Comment by castle024** [comment]
> Somebody suggested that Junk Store might be the problem and that its latest update might be the solution. This is the standalone Junk Store 2 that I paid for so that I can easily integrate my GOG games into Steam OS.
> 
> There was some discussion of a similar problem at Junk Store's Discord server and it seems like the update solved it for them.
> 
> I updated Junk Store and re-installed Decky Loader, but I still can't boot up without that error message unless I uninstall Decky Loader.

That was me, but I deleted the comment because I noticed it was the same error just presented in a different way, and I didn't want to confuse people. If I uninstalled Decky the boot error with the options to start without Decky, restart Decky, restart steam, etc, went away, but when Steam booted there was  another "cannot render content" window. This was fixed when I updated Junkstore. Moral of the story is that Decky and Junkstore were broken with the update. Junkstore is fixed, but I still have a Decky problem even after a complete wipe, without any plugins installed.

**Comment by jullson2** [comment]
Nope. I use MuraDeck and Steamgriddb, nothing else. But Decky doesn't work with SteamOS at the moment. I have cleared alls settings, folders and made a clean install and it still doesn't work. Tried it on my second deck (LCD) and it's the same. Seems like an issue with Decky.

**Comment by Rumik** [comment]
No, I don’t use JunkStore.

**Comment by VAggrippino** [comment]
> I checked the issue author logs and found multiple errors, ex:
> 

> After you clear your `plugins` folder, make sure that you make a reboot in order to see if everything was fixed.
> 
> P.S: I'm on latest Beta Steam Update with same Decky version as author, but on my machine everything is fine 🤔
> 
> There is not enough details what you guys have in common what can cause this error

I've updated the screenshots in my initial post and generated new log files.

I've rebooted many times since removing the plugins. I've also rebooted after completely removing Decky Loader and after completely removing `~/homebrew`.

I don't know what any of those error messages mean, but I did notice messages from plugins I don't have installed including some that I uninstalled long before I ever had any problems.

For example, I uninstalled Emuchievements a while ago but continued to use Decky Loader and other plugins without any problems:  
```
[1111/180809.393350:INFO:CONSOLE(5748)] "Uncaught Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`", source: decky://decky/legacy_plugin/Emuchievements/index.js (5748)
```

I don't know where it's getting these. My plugins directory is completely empty:  
```
(deck@steamdeck ~)$ ls -AlR homebrew
homebrew:
total 12
drwxr-xr-x 2 root root 4096 Nov 18 09:02 plugins
drwxr-xr-x 3 deck deck 4096 Nov 19 05:29 services
drwxr-xr-x 2 deck deck 4096 Nov 18 09:02 settings

homebrew/plugins:
total 0

homebrew/services:
total 26624
-rw-r--r-- 1 root root        7 Nov 19 05:29 .loader.version
-rwxr-xr-x 1 root root 27251896 Nov 19 05:29 PluginLoader
drwxr-xr-x 2 root root     4096 Nov 19 05:29 .systemd

homebrew/services/.systemd:
total 8
-rw-r--r-- 1 root root 379 Nov 19 05:29 plugin_loader-backup.service
-rw-r--r-- 1 root root 406 Nov 19 05:29 plugin_loader-release.service

homebrew/settings:
total 4
-rw-r--r-- 1 root root 134 Nov 19 06:16 loader.json
```

**Comment by VAggrippino** [comment]
> That was me, but I deleted the comment because I noticed it was the same error just presented in a different way, and I didn't want to confuse people. If I uninstalled Decky the boot error with the options to start without Decky, restart Decky, restart steam, etc, went away, but when Steam booted there was another "cannot render content" window. This was fixed when I updated Junkstore. Moral of the story is that Decky and Junkstore were broken with the update. Junkstore is fixed, but I still have a Decky problem even after a complete wipe, without any plugins installed.

I figured it was something like that, but I read the conversation thread and some of Junk Store's other troubleshooting information and didn't find a solution for me. In Junk Store's Troubleshooting FAQ they mention a similar error and their solution is just to update Decky: https://www.junkstore.xyz/2.0troubleshooting/#junk-store-not-working

I installed the latest version of Junk Store Pro (2.1.0.0) and re-installed Decky Loader but it's still broken for me.

**Comment by ynhhoJ** [comment]
Do you guys use Steam Beta Channel Updates?

If yes, can you try to change it to `Stable`?

**Comment by VAggrippino** [comment]
> Do you guys use Steam Beta Channel Updates?
> 
> If yes, can you try to change it to `Stable`?

I don't use beta but you said you did and you're not having this problem. So, I considered switching _to_ beta.

**Comment by ynhhoJ** [comment]
@VAggrippino , what do you have on `4242` port?

<img width="2414" height="405" alt="Image" src="https://github.com/user-attachments/assets/d9c87cd9-a000-4142-aad2-c483ce813628" />

Even on last logs, it is here:
```
[10019:10019:1119/061807.674777:INFO:CONSOLE(1)] "TypeError: ImportCall("http://localhost:4242/loader/index.js?c=3972539872") is not a function", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=d7d898731ea6f6080907 (1)
[10019:10019:1119/061810.109695:ERROR:atom_cache.cc(229)] Add _NET_WM_STATE_KEEP_ABOVE to kAtomsToCache
```

It seems to me that the reason of Steam Deck UI crash is somehow related to this `ImportCall` which fails.

**Comment by VAggrippino** [comment]
> [@VAggrippino](https://github.com/VAggrippino) , what do you have on `4242` port?
> 
> Even on last logs, it is here:
> 
> ```
> [10019:10019:1119/061807.674777:INFO:CONSOLE(1)] "TypeError: ImportCall("http://localhost:4242/loader/index.js?c=3972539872") is not a function", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=d7d898731ea6f6080907 (1)
> [10019:10019:1119/061810.109695:ERROR:atom_cache.cc(229)] Add _NET_WM_STATE_KEEP_ABOVE to kAtomsToCache
> ```
> 
> It seems to me that the reason of Steam Deck UI crash is somehow related to this `ImportCall` which fails.

It looks like that's part of Junk Store. I just updated that, thinking it was part of the problem. I didn't see any uninstall instructions for Junk Store, so I'll have to do some digging to figure it out. I guess there must be a `systemctl` service?

```
tcp        LISTEN      0           50                   127.0.0.1:4242                 0.0.0.0:*          users:(("junk-loader.run",pid=121392,fd=7))       
```

**Comment by ynhhoJ** [comment]
@VAggrippino , I'm not familiar with JunkStore, but can you try to search in your system?
Maybe you can try to search by keywords like `junk`, `junk-loader` and etc

**Comment by Rumik** [comment]
Okay yeah I backed up my plugins and data and wiped Decky. Then reinstalled one by one and restored their settings. Not sure which was causig the issue but it's fine now.

**Comment by jullson2** [comment]
I found the culprit! Muradeck!

**Comment by WAR282737** [comment]
How did you remove the plugins? When I press restart without the decky loader, the console gives me a black screen and none of the buttons work...

**Comment by jullson2** [comment]
Go into desktop mode and use the decky installer to wipe it! Wipe, don't keep any settings. Backup any important data first in the homebrew folder

**Comment by ZeroFoxx** [comment]
Had the same issue, I tried sudo rm-ing a few plugins and I believe a few including MuraDeck are to blame. Just wish there was a way to temp disable plugins to troubleshoot crashes like this.

you dont have to fully wipe decky from what i tested, just try running `sudo rm -rf /home/deck/homebrew/plugins/(plugin)` first

**Comment by SiTWulf** [comment]
Due to problems like this, a request was made about two years ago to allow [plugins to be disabled](https://github.com/SteamDeckHomebrew/decky-loader/issues/350) without uninstalling them, but the request was completely ignored. A perfectly reasonable request that would have prevented problems like this was quickly forgotten by everyone.

For cases like this, it would be so simple to disable the problematic plugins and then reactivate them once they are updated...

**Comment by revlisoft** [comment]
Same issue here. Had to disable entire plugin by booting into desktop mode. Never used the junk store either so no clue what that is.

**Comment by VAggrippino** [comment]
Based on the conversation here, it seems that there's more than one way to trigger this issue.

I've had a brief conversation with the developer of Junk Store. He's aware of the issue and investigating a conflict between Junk Store Pro (the paid version, not the Decky Loader plugin) and Decky Loader.

For me, with no Decky Loader plugins installed, the problem is probably caused by a conflict between Decky Loader and Junk Store. But there are people experiencing the same or similar problems that have never used Junk Store. There's probably something going on here that the Decky Loader devs could take a closer look at, too.

**Comment by KaliEros** [comment]
I started experiencing the same error message a few days ago. Well, the error reference was the same, but the first few times it said that the problem was with Steam. It also didn't list a specific plugin as the culprit like it did when I had an issue with MagicPods months ago. A few times when the error message popped up, it even kept turning my screen black for a few seconds, like a mini-restart, then it would come on again, go black again etc. So, I only had a few seconds to tap "Restart without Decky" before it would go black again. 

Anyway, I eventually deleted every plugin except for 3 that I consider essential and finally got Steam to start in Desktop mode without the error message. I thought that fixed it as I didn't get another error message for about a day. Then it popped up again this morning. Except now it's saying that the problem is with the Decky Frontend and it's finally listing a specific plugin: SteamGridDB. 

When I get back home, I'll try uninstalling every plugin, restarting, and reinstalling my top 5: ProtonDB Badges, Power Tools, Storage Cleaner, Cheat Deck (for those games I've already beaten and don't want to grind a lot on), and SteamGridDB. If that doesn't work, I'll try wiping Decky completely rather than just uninstalling and see if that fixes it. 

I should also point out that I don't have the latest Steam OS. I forget exactly which OS I'm on, but I haven't updated in months. The reason is that, according to the comments on Steam, every update seems to come with quite a few problems, some minor and some not so minor. It's made me very hesitant to update unless I see one where the comments don't include multiple people saying it bricked their Steam Deck. If it ain't broke, don't fix it. 

One other thing I want to mention that I find strange is these error messages don't take up the entire Steam Deck screen. When I had a problem with MagicPods, that error message took up the entire screen. This set of error messages over the past few days takes up roughly a third of the top left screen. So, I can still see the game I'm playing, the website I'm on etc. I don't know if that matters at all, but I thought I'd mention it. 

Well, I'll update on my progress with these errors. Hopefully everyone experiencing this can get it fixed ASAP.

**Comment by DClem85** [comment]
I just removed all my plugins and tracked my issues down cheatDeck.

**Comment by N0Klu3** [comment]
I too am having this issue.

I only have CSS plugin for some views.
Removing plugin didnt help for me.

**Comment by Kondios** [comment]
The same problem. Exactly the same error message. Uninstalling and reinstalling does not help.

**Comment by ericswpark** [comment]
Had the same issue, bisected it down to the ShareDeck-y plugin causing the crash-loop. Moved it out of `~/homebrew/plugins` and the issue stopped.

Side note: [ShareDeck-y](https://github.com/davocarli/sharedeck-y) seems to be unmaintained and has been delisted from the plugins listing page, so perhaps it is not supposed to be used by users anymore. In that case Decky should probably warn users that they have unsupported plugins installed, before the next update comes and breaks them (like now).

**Comment by WildFyr16** [comment]
I had this issue only in the Decky menu, so I updated to see if the issue will be fixed. Now I am stuck in a boot loop where the whole screen shows this error and the device restarts. I am on the latest Steam OS and Decky release

**Comment by AntiMatterDotA** [comment]
I had this issue with the same splash screen as OP. Boot loop continued until disabled Decky. Read through the thread and I am not using any of the stated plugins that others removed to fix the issue nor Junk Store. I do have quite a few plugins but I wasn't able to figure out which were/weren't causing the issue. Just wanted to add another recognition of this issue.

Issue happened today after updating SteamOS and Decky both to the latest stable versions. I then updated various plugins and the last plugin seemed like it failed, might have been "mango hud" but as that was what caused the error it was only on screen briefly so I might be mistaken.

Performed a reinstall of Decky and restarted the deck leading to the boot loop issue returning. As of now I've just left Decky uninstalled until a fix is found for whatever is causing the issue.
